#!/bin/bash

GREEN='\033[0;32m'
BLUE='\033[0;34m'
CYAN='\033[1;36m'
RED='\033[1;31m'
PURPLE='\033[0;35m'
NC='\033[0m'

line=$1
departure=$2
destination=$3

function check_binaries() {
  jq="$(which jq)"
  pup="$(which pup)"
  if [ -z "$jq" ] || [ -z "$pup" ];
  then
    echo "You need to install jq and/or pup."
    exit 1
  fi
}

function strip_quotes() {
  sed "s/['\"]//g"
}

function strip_spaces() {
  sed "s/\ //g"
}

function strip_newlines(){
  sed "s/\n//g"
}

function train_url() {
  echo "http://metrarail.com/content/metra/en/home/jcr:content/trainTracker.get_train_data.json?line=$line&origin=$departure&destination=$destination"
}

function alerts_url() {
  echo "http://metrarail.com/content/metra/en/home/jcr:content/trainTracker.serviceannouncements.html?trackerIndex=0&trainLineId=$line"
}

function get_html() {
  curl -s "$(alerts_url)" | tr -d "\n"
}

function get_json() {
  curl -s "$(train_url)" | tr -d "\n"
}

retrieved_json=$(get_json)
retrieved_html=$(get_html)

function check_for_alerts() {
  link_text=$(echo "$retrieved_html" | pup '.delay text{}' | tr -d '\n' | sed 's/^\ *//g')
  detail_text=$(echo "$retrieved_html" | pup '.delayDetails p text{}' | fmt -w 100)
  if [ ! -z "$link_text" ] || [ ! -z "$detail_text" ];
  then
    echo -e "${RED}Metra posted an Important Message regarding your train line:${NC}"
    echo "$link_text"
    echo
    echo "$detail_text"
    echo
  fi
}

function check_for_errors() {
  if [ "$(echo "$retrieved_json" | jq ".train1" | jq "keys" | jq ".[0]" | strip_quotes)" = "error" ]
  then
    echo -e "${RED}There are no trains scheduled for the specified route currently.${NC}"
    exit 1
  fi
}

function get_train_hash_numbers() {
  echo "$retrieved_json" | jq "keys" | jq ".[2:]" | jq "@sh" | strip_quotes | tr -s ' ' '\n' | sort -n -k1.6
}

function get_train_designations() {
  echo "$retrieved_json" | jq ".$train_number.train_num" | strip_quotes
}

function is_late() {
  echo "$retrieved_json" | jq ".$train_number.hasDelay"
}

function departure_meridian() {
  echo "$retrieved_json" | jq ".$train_number.schDepartInTheAM" | strip_quotes
}

function departure_time() {
  echo "$retrieved_json" | jq ".$train_number.scheduled_dpt_time" | strip_quotes
}

function departure_time_update() {
  echo "$retrieved_json" | jq ".$train_number.scheduled_dpt_time_note" | strip_quotes
}

function departure_time_estimated() {
  echo "$retrieved_json" | jq ".$train_number.estimated_dpt_time_note" | strip_quotes | strip_spaces
}

function arrival_meridian() {
  echo "$retrieved_json" | jq ".$train_number.schArriveInTheAM" | strip_quotes
}

function arrival_time() {
  echo "$retrieved_json" | jq ".$train_number.scheduled_arv_time" | strip_quotes
}

function arrival_time_update() {
  echo "$retrieved_json" | jq ".$train_number.scheduled_arv_time_note" | strip_quotes
}

function arrival_time_estimated() {
  echo "$retrieved_json" | jq ".$train_number.estimated_arv_time_note" | strip_quotes | strip_spaces
}

function determine_schedule() {
  if [ "$(departure_time)" = "$(departure_time_update)" ];
  then
    departure_time=$(departure_time)
    departure_meridian=$(departure_meridian)
  else
    departure_time=$(departure_time_update)
    departure_meridian=$(departure_meridian)
  fi
  if [ "$(arrival_time)" = "$(arrival_time_update)" ];
  then
    arrival_time=$(arrival_time)
    arrival_meridian=$(arrival_meridian)
  else
    arrival_time=$(arrival_time_update)
    arrival_meridian=$(arrival_meridian)
  fi
  if [ "$(is_late)" = "true" ]
  then
    echo -e "${RED}This train is running late:${NC}"
    departure_time=$(departure_time_estimated)
    departure_meridian=$(departure_meridian)
    arrival_time=$(arrival_time_estimated)
    arrival_meridian=$(arrival_meridian)
  fi
}

function display() {
  check_for_errors
  check_for_alerts
  trains=$(get_train_hash_numbers)
  for train in $trains
  do
    train_number=$train
    determine_schedule
    echo -en "Train number ${PURPLE}$(get_train_designations)${NC} is departing at ${CYAN}$departure_time $departure_meridian${NC}"
    echo -en " is leaving from ${GREEN}$departure${NC} "
    echo -en "and is arriving at ${CYAN}$arrival_time $arrival_meridian${NC}"
    echo -e " and is going to ${BLUE}$destination${NC}"
  done
  exit 0
}


check_binaries

case $0 in
*metra_tracker_test*)
  :
  ;;
*)
  if [ $# -lt 3 ]
  then
    echo -e "${RED}You need to specify the train line, departure station, and destination station!${NC}"
    exit 1
  fi
  display
  ;;
esac
